### ISSUE TITLE
Unified soraka

### ISSUE THREAD

**Issue by Michael-Gibbons** [victorgrego/Bol#5]
Your last update to unified soraka required the user to have the VIP membership(more like membershit) just curious, have a nice day

[string "Serialization = {
..."]:469: attempt to cal Global 'CLoLPacket' (a nil value)

**Comment by victorgrego** [comment]
Yes, it does require. Main Bol functions are out of work. If you don't like VIP just don't buy, no rudeness needed.


--

Victor Nascimento





On Mon, Aug 17, 2015 at 1:14 AM -0700, "cavemanxx130x" <notifications@github.com> wrote:
Your last update to unified soraka required the user to have the VIP membership(more like membershit) just curious, have a nice day

[string "Serialization = {
..."]:469: attempt to cal Global 'CLolPacket' (a nil value)

---
Reply to this email directly or view it on GitHub:
https://github.com/victorgrego/Bol/issues/5

**Comment by Michael-Gibbons** [comment]
No disrespect to you lol i think you are a very intelligent person i was just trying to make a joke ^_^ have a nice day
